// Generated by CoffeeScript 1.12.7
(function() {
  var Hs, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Hs || (root.Hs = {});

  Hs = root.Hs;

  $(function() {
    var start_action;
    $(".menus").on("click", ".menu_item", function(evt) {
      var data_name;
      $(".menu_item").removeClass("menu_item_current");
      $(".menu_main").addClass("hide");
      data_name = $(this).attr("data-name");
      $(".menu_item[data-name=" + data_name + "]").addClass("menu_item_current");
      return $(".menu_main[data-name=" + data_name + "]").removeClass("hide");
    });
    start_action = function() {
      return $(".menu_item[data-name=bitfeg_create]").click();
    };
    return start_action();
  });

}).call(this);
